export const routes = {
  home: '/',
  bangGia: '/bang-gia',
  about: '/about',
  dieuKhoan: '/dieu-khoan-dich-vu',
  chinhSach: '/chinh-sach-bao-mat',
  checkout1: '/checkout/1',
  checkoutPlan: '/checkout-plan',
  checkout2: '/checkout/2',
  register: '/register',
  login: '/login',
  forgotPassword: '/quen-mat-khau',
  resetPassword: '/dat-lai-mat-khau',
  verifyOtp: '/verify-otp',
  checkout: '/checkout',
  payment: '/payment',
  capNhat: '/cap-nhat-nen-tang',
  taiNguyen: '/admin/tai-nguyen',
  dashboard: '/dashboard',
  dashboardCaiDat: '/dashboard/cai-dat',
  dashboardWallet: '/dashboard/wallet',
  dashboardLichSu: '/dashboard/lich-su',
  dashboardGoiCuaToi: '/dashboard/goi-cua-toi',
  dashboardModelLora: '/dashboard/model-lora',
  dashboardWorkflows: '/dashboard/workflows',
  dashboardStorage: '/dashboard/storage',
  dashboardStorageCheckout: '/dashboard/storage/checkout',
  bangGiaCheckout: '/bang-gia/thanh-toan',
  admin: '/admin',
  adminKhachHang: '/admin/khach-hang',
  adminHaTang: '/admin/ha-tang',
  adminInfrastructure: '/admin/infrastructure',
  adminCustomers: '/admin/customers',
  adminHourGrants: '/admin/tang-gio',
} as const;

export type RouteKey = keyof typeof routes;
