/**
 * A1 M2 — Offline Supported Node Manifest catalog (Worker).
 * Data generated by scripts/build-supported-node-manifest.mjs
 */

import {
  SUPPORTED_NODE_MANIFEST,
  SUPPORTED_OBJECT_INFO,
} from './catalog-data.gen.js';

export function getSupportedNodeManifest() {
  return SUPPORTED_NODE_MANIFEST;
}

export function getSupportedObjectInfo() {
  return SUPPORTED_OBJECT_INFO;
}

/**
 * @param {string} nodeName
 * @returns {unknown | null}
 */
export function getSupportedObjectInfoNode(nodeName) {
  const key = String(nodeName || '');
  const catalog = SUPPORTED_OBJECT_INFO || {};
  if (Object.prototype.hasOwnProperty.call(catalog, key)) {
    return catalog[key];
  }
  return null;
}

export function offlineCatalogMeta() {
  const m = SUPPORTED_NODE_MANIFEST || {};
  return {
    capture_status: m.capture_status ?? null,
    complete: Boolean(m.complete),
    node_count: m.catalog?.node_count ?? Object.keys(SUPPORTED_OBJECT_INFO || {}).length,
    manifest_id: m.manifest_id ?? null,
    lock_sha256: m.provenance?.lock_sha256 ?? null,
  };
}
